apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: cloudflared
    targetRevision: 2.2.8
    helm:
      valuesObject:
        tunnelConfig:
          name: "homelab"
        tunnelSecrets:
          existingPemFileSecret:
            name: "cf-secret"
          existingConfigJsonFileSecret:
            name: "cf-secret"
        ingress:
          - hostname: "murfzw.nl"
            service: http://echo-svc.echo.svc.cluster.local
          - hostname: "*.murfzw.nl"
            service: http://echo-svc.echo.svc.cluster.local
          - service: http_status:404
  destination:
    namespace: cloudflare-tunnel
    server: https://kubernetes.default.svc
