apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: cloudflared
    targetRevision: 2.2.9
    helm:
      valuesObject:
        tunnelConfig:
          name: "homelab"
        tunnelSecrets:
          existingPemFileSecret:
            name: "cf-secret"
          existingConfigJsonFileSecret:
            name: "cf-secret"
        tolerations: []
        ingress:
          - hostname: "murfzw.nl"
            service: http://echo-svc.echo.svc.cluster.local
          - hostname: "ptcgl-api.murfzw.nl"
            service: http://ptcgl-api.ptcgl.svc.cluster.local:8080
          - hostname: "ptcgl-assets.murfzw.nl"
            service: http://ptcgl-assets.ptcgl.svc.cluster.local:8080
          - hostname: "ptcgl.murfzw.nl"
            service: http://ptcgl-web.ptcgl.svc.cluster.local:3000
          - hostname: "*.murfzw.nl"
            service: http://echo-svc.echo.svc.cluster.local
          - service: http_status:404
  destination:
    namespace: cloudflare-tunnel
    server: https://kubernetes.default.svc
