---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgCLOMEdHElnnwhYe1V2y3cSXrFYVO8XLEbaCtK9hay4sbqnu0X99cXdOCDZ+vEwGWeXdsTGZaxtOfVNbs64kvcAjNnauP5QEabCWQNx2VmmynV3ZYHDwqVOinzRl4uJdGgwS3bK/2mEtWg25iPeI2jddxEPSULcq9dl+u50sTUURma7HOl1YbajiSi4FEvSIo161Wm+h3G36/mIKzsAPXmqIbsTs19tlQPK2DUL2TYRotNTQnMWHlkfes13JZSME5w97DPNf9gMutg2u/IPVnaaghJYn4/G3psM7WgKOQ3OFVQN8LrUpm4SPODyYNiWz/9i9oz9wB2CbmAQc4uSuIwYpHN2iYVfxLSsIRYQhUNRv2ebda9H19DDpphHpBniL/gNaPifD9+65i/xbAo2kRHk/9OdMRIotjy+xe2PBuoVLlnO5zmaZHszkHowyLvFXKozyAUlw25PiTLWTEbIsJRw6Jde8AOs52PUMF3xgMdbXp6qK48JjvBPBGNPDH3Ko4972ZpkFEE+d+awjsvTgkJvGtdYpgWsWUcM8mVsyvLNrx+Rlpk5SaL7GmKHGwT0oHEsqZQwvje3GaivISX6lJvOFosXfugfiYSxybNEb+qWcSK+ogObkfNfBsKRTKytogYhMRkqyQhIPNPzNJmK/5/ZlmthTZyjxn7QpLGb5A0XhnPaAOM9uz+aDEG7g3hcT/9xT/t5b9tStea6635V9DqusZhJjux6USDfck/g0GSxqzbEfsO8XQTYoD2JdgM0/ZzjfelKKAmJc7lRMaMutq+abohrE1FfEFsYWNh71VlvgqSXzEdvAMNVFuN6N+B576xReHn0dHW3EzITsdwPDH23XGh5R8czVOgl5VuQrL4qHLL0o0w6cp5mZr0E32NNF3toyuR20W3Wsawjy/P+PMV+/Q==
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflare-tunnel
    type: Opaque
