apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.13.1
    helm:
      valuesObject:
        args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
          - --metric-resolution=15s
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        replicas: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
