apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    glance/icon: di:tailscale
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.98.9
    helm:
      valuesObject:
        apiServerProxyConfig:
          mode: "true"
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
