---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBRSdDiaUQqXhnsxpp0IzqgDrrK2SdonSEgBZGz1jCLUlh/ZeRolv5npExDg1AlUTeNEtbUvQ3wHNpTDb2sA/MtqV8QNC1Frz6IZbUUyEr5GgOfO+nX5ULWPi6UCJL85u/kfO13IFJ4jqh+JDKhLkmSMYsTxz/AWAKtaywEZT3GivTexp3xa86CcQbO/DuV6bqsPsCot33RIcd0lXrFYNcqCG/fN2BfLiEoypNiCgMZBH0DdLA71BlEBGByRgzDkV79jHQgb12T5m8RwIacQP+J6LU4PxomY9ULkqX4I9DVxJfDAeWekyNCQiRRacIg3uMCQmJ3JuMd+Im+ztNfsLohbOzELcr+wnRM13wwjKzoZSqqF7ppqkRw0pvi2G4V8670U7+0G99C3FO6jwDcIGa4NK+zupBIg3IVzcxKK+eI6UqeoiBNuC5KQKlTfCkObtEbrRUtw7dkUg0tS9PSFXuMrVuJtyO32lyI9PWpWgkAi5Y2NO6eAsKd/QzaF13vcdb4P6GMITjHDfZwkeppAsMWFRc3mR+xUr9Lz8cdLG5b8pfYwQKW6AA2ds1MZREmP7aRihuiHhQlIpvtYkqUaCfxpx875SnVXbFZ/byp0JQYI1xSboj+uW67NHnp4UyWNCSd5/nO66nljbIsVC1chLkfmL3xX1dWtzNuQseXkHntrlxMCYE/PiD9HT1mo8BRMIiPIss/T96tJt+HgdSMF+KPmw==
    client_secret: AgA1sI4PXvsmh24lNIodM6ePjtjwwaTMzv0eZA4ujwn0fdW841yApgR6A8ZM6KjhejSHKeWOBNRCQeOD2myVA1DpQrx5KvivLNW2fcpbqfJvg9aGJIuMd8GuQKWJ10TxvIVmTGdM+jRBYNAWShk/yBoh+ZzVGlBTOdue4wbfTWBFdiVc4Ve2Mx2/kn2T0FSeHtZXUawSC9rBRpM0mQHRwkfs6W0MErgRthRD/YO4D4A6kiNkwTdRHhPOrc73wumiq87Vq4P39iyyHQDMOPRsDWv2JlF3gxhdo0/Ic7GYkfLkNEYUkhPVxq4pH01QwNCeVpvXLGxn0BkXVQf34mJ1eFi7hdBSJl7IvaKDDcgEr8a6h79ZKdiQOxiu49vOLdC7qc1i18YCe+1kX82IBPOeYXmU1UP5eOrEmPl3TdEZGnYQRiMPwIlmQ4mWeqYX4c/KzIBuROpp1pB6f7sCt5pmGISMkMcf3sUJ4ebM6KQ2w5qhbmV7AdtLPIMvLD7JVf8pyjE58ksy84u9awNmbwI+JvFCqNU141bZYDhBaG3uDZ6nlL5867Fx1SYybPS6qxuNloDiDX/P8296yxBRKzMMJ0zC5CNNKUsTTEXqzHK0B3nk2+tKZA8E65zjbtfGzN7Azaz2LMUrMgDxRGUTgSXowgMtill2CIE2Kjygc4xej4V6qT761++iHiL5veMMvEUR6+N09eYoUodeXFspMIk2ve4Zvss8qDNTetbE3H0vIMZHi7Sp43b0F2JfAsqY5OLrm8w53ox4wWCQpWVlXT89U5di
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
