apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      valuesObject:
        cloudflare:
          tunnelName: "homelab"
          tunnelId: "e619bd2a-64b8-48b0-a9d0-cda9dfa7d2b0"
          secretName: "tunnel-credentials"
          ingress:
            - hostname: "murfzw.online"
              service: http://echo-svc.echo.svc.cluster.local
            - hostname: "sharry.murfzw.online"
              service: http://sharry-svc.sharry.svc.cluster.local
            - hostname: "*.murfzw.online"
              service: http://echo-svc.echo.svc.cluster.local
            - hostname: "access.ptcgl.online"
              service: http://auth-server-svc.ptcgl.svc.cluster.local
            - hostname: "ptcgl.online"
              service: http://frontend-svc.ptcgl.svc.cluster.local
            - hostname: "assets.ptcgl.online"
              service: http://assets-svc.ptcgl.svc.cluster.local
  destination:
    namespace: cloudflare-tunnel
    server: https://kubernetes.default.svc
