apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    chart: home-assistant
    targetRevision: 0.3.20
    helm:
      valuesObject:
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          className: tailscale
          hosts:
            - paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - home-assistant
        configuration:
          enabled: true
          forceInit: true
          trusted_proxies:
            - 10.0.0.0/8 # k8s
        persistence:
          enabled: true
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
