apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorio
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://sqljames.github.io/factorio-server-charts/
    chart: factorio-server-charts
    targetRevision: 2.5.2
    helm:
      valuesObject:
        rcon:
          external: false
        image:
          # renovate: image=factoriotools/factorio
          tag: "stable@sha256:e2962a9a28701da4deaf2b5192ec7dc26b5ff15480da87c352355d596e648d2a"
        persistence:
          enabled: true
        factorioServer:
          save_name: "Lets goooooo"
        serverPassword:
          game_password: {{ .Values.factorio.game_password | quote }}
        admin_list:
          - murfzw
        server_settings:
          name: "F&M"
          description: "To the moooooon"
          visibility:
            public: false
          require_user_verification: true
          autosave_only_on_server: false
        service:
          type: LoadBalancer
  destination:
    namespace: factorio
    server: https://kubernetes.default.svc
