apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole-external-dns
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 8.6.1
    helm:
      valuesObject:
        provider: pihole
        policy: upsert-only
        txtOwnerId: "homelab"
        pihole:
          server: http://pihole-web.pihole-system.svc.cluster.local
        extraEnvVars:
          - name: EXTERNAL_DNS_PIHOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pihole-password
                key: password
        serviceAccount:
          create: true
          name: "external-dns"
        ingressClassFilters:
          - nginx-internal
  destination:
    namespace: pihole-system
    server: https://kubernetes.default.svc
