apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.86.5
    helm:
      valuesObject:
        oauth:
          clientId: {{ .Values.tailscale.clientId | quote }}
          clientSecret: {{ .Values.tailscale.clientSecret | quote }}
        apiServerProxyConfig:
          mode: "true"
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
