apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.26.2
    helm:
      valuesObject:
        DNS1: 1.1.1.1
        persistentVolumeClaim:
          enabled: true
        ingress:
          enabled: true
          hosts:
            - "pihole.home"
        serviceWeb:
          loadBalancerIP: 192.168.1.153
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        serviceDns:
          loadBalancerIP: 192.168.1.153
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        replicaCount: 1
  destination:
    namespace: pihole-system
    server: https://kubernetes.default.svc
