apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aviator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/zwolsman/go-aviator
      targetRevision: HEAD
      path: infra/base
    - repoURL: https://lucasdpt.github.io/frpc-helm-chart
      chart: frpc
      targetRevision: 1.0.1
      helm:
        valuesObject:
          frpc:
            existingSecret: "frpc"
            serverAddr: "eu4.joell.dev"
            serverPort: 6969
            proxies:
              - name: ssh
                type: tcp
                localIP: 10.111.98.217
                localPort: 2222
                remotePort: 22
  destination:
    namespace: aviator
    server: https://kubernetes.default.svc
