---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: go-aviator-host-key
  namespace: aviator
spec:
  encryptedData:
    host_ed25519: AgBU4bsJ7ETodIcclZl33Nioyc3b16wE4ADyg5WgV/cZNsp9ncdBZV0T1b+MnKB/h0j+1n99U9S38seGVnJ5N/wLrvXS4rUVa3DALYLxdN6/vYOy5dnpCX3EGUJzsjFZF2ExKKurKKdYxHJDTXjpq9BGO9Yc2z/IVvvYuI9oFTZncv9nvoj8y1HAaoY08r9aTwOg3fUw/gyQKRX4W+vdp28JxZc6xNvTR64VT6+4GuTYxRJPBoLLba6yjdq++6uzJL+CCR2MozB32nSKacXAl9FmLoYVbfmjttzOPgli4QwL6qE2LJtm8RhUWWUaHaJH0fFQpR76ughoq8mCxBb2c+CClEkwX8YgjCBNqqoKYkB9NIvd/bOtwfiATDE8tuf76OwD7CyiOuRww80fczKJW5wiG0AjhjZDn5caDOU1mNk+Uu+hFdvK7W3JGqu07QsNp/GCBG/VcHmQInZoGvpSZgtHuXklBGIhIOjC8VUxgFNQD4ORqBi4z6Amlx/I5FpnmBVRjo7YQgypBabq+Xu8ju55H9nnY4tbjYbImlu+A340c4eupIkQAt7EpbhWq5CsFZSPiv+c7V0iSwoX9IH77V2Ya6ZlRyjD+erx+42NX8p66csEoTtGUuD1g6HJ75yPvkavP8DnDDUlrwdPnu4LHHiyr7nSq/Izzu60PSGYw9Tyja7nn6LPYCNC0mr2k7f3i7a7+9iprvcDajqLukEuQBiUyXYnegbmDX4LAnQBi86vea/2s5ZbYFny37WZ+Za6y62Di0282MZvd36Un/Xy8CNTZ/hfniukg8u6ohZXapqnZg++RUpBHBBx6OpEZS9vzs8U5nUrnCqedzMWx///6S2n24a8ML5h1GnXh4UKlNcx/FaM4l3LtynjOd88h/yP7cGX10isMLfaIOz/vdqpnpUdLSUcpM9YFmyoOyYAFeQJesoXvQXcYN3IUGzXXxEdM3pizpKUMAP378s9wPId9pz2FcsSIaj+MLZzL2lEO5hl3lsD2yp+dB/5qd4AjV2cHHzNyJyG8vuanw8j5uBhk4CgxX8v3ToYwrzpwhh7iYWu8pt2ylmyt38jQgEnF/QjOwfqSe9rwzavj9V4W4mqkc5LilbyMT/MTfS+TXTXoj1N7G/y/vzJ+35M8qrAB+vfI1q9fdvclj0j4BWciD6E0LhgOqimDR7vjlaPEclGPZy2NR36RlSgwK2vR2HreOgXK3zUjfCZcTWq0Hu4GDtoTVko0jrmIMKqAcpYMJudZy0o7DQHDg==
  template:
    metadata:
      name: go-aviator-host-key
      namespace: aviator
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: go-aviator-db
  namespace: aviator
spec:
  encryptedData:
    url: AgBWBvaKLb/dVrCwenoWNaN7dxhytZ8szWbFrsheEbqlOfVgnCDGzG9gZq/63VPVlhp0toRVJNrlUC7ZUePB29oUz+MaIofxspWv4XxIZbtwLvJNPxkoZl6XXrEcLMyG6iZ8aVyqqhK5BHljI0hGUcrRPVn33VhkrvYGKLX68/i/Z2bTiEFgFn0o76Kf/Uclx4oEtL2J5n1q1172BzhaWV/HH5sY6Xh8RdI5U22P5Fp3qCEmwb5WyViJn52Ht89c2xYsVT+WaGKB8sgBDcfU/TVZHhQ0Z4XYJs8p7+tEYXbXFldqrDyns9RnRSIMFNHZxinUQQWNyaaXl1Esla27OrwP/RljjH21+BiMTZliVi7Y5Yv41PwCVKh7JBztT/j6T5gBXW4Z7nffChc97NkzrqSNffp8/DzvFky0ny/OWBDQgGoXzC9QkASXBMWj7OSLLZdRgz0KOlYt6DqoaYi/b9kvc/czZtq6kaUzBVApeI6jThkYWKlRKxwJwyrniMLpJi2Qw4IpdlPKgX3YGDHZrg4PnJVJhUbysSkFOFTrB8E0JCTQxTg+LATDv3HJQXSu/aYbRs/2g+R0QhkVX1UyQ0JM62XHccUJCu5irovGaBqYdfEPyJuS3a1sJqr2zK7ZsN1lhUHKtcV8dqcrLvQKzrnlmmjhGDUhEHxI90Xt7vy+f2NRdA006ACdugLBOcBi3NlZ5fwpJMsZ8oMj/O07YdAxlc/J2MhQMqrN+b1OM9h5UZUlvzsvz1otfTvOhMYFAfa6yF7JrvHzE4jvddB5P4YaXuk2gWEMxnQAX0JXFLkh5acLGq7SHp/F2SZqPcUmkRkau4+C04l49Ju09m3BKhOAIQM4uGeTm1QCmfa6xeFZhh5fUJD98lHAohhLWDSz3+iTXBeRYOmlqwSSbjmWsdbOVBY=
  template:
    metadata:
      name: go-aviator-db
      namespace: aviator
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frpc
  namespace: aviator
spec:
  encryptedData:
    token: AgBCgUYNhIGrPfE+fHBVWWYEdb9rH6hJFAGr1GWOxbUNSjdo/e1axYi/0hV/fRgT86q380w/Bt3LCtJRgFxxdvoIp3POxxL89ob22fzxc3MiyGsp1ks+GTA+0TXvfolKunSqjNI2j7R9PjhE3cso82VSZEd6iTm6AE15aMFh/J5VcKu+OFlu+OSTVFKq7FTrLOpMWnSIFLMd/wq09b5jox4RB4524TYFi+NgCsPzdys2meDsCZfk4XhCVVALM6TdgC/gs7Lni6jAR4YJuRiONRbPE5UzonIK+yPlqoINS97p12lZOAyA+Bi2PGfFiOszUTu9r2xni2lnR49EFybZ0df6fj6I/EFbqcuQbN5OTkpMjCPX8VIpEaLlhXg30grpTmILd7kdnwHGaJE0uxH8OnnkBZ9cPvZ00N1izrcCBdN1Vf8FQzfgvqSBlP+/qEFNCz0g5ytMpW/B/xv+aImM7/A5aJiwTw73Y8rTKfNnk+xxG4sRvF22+nYYgyRVl13nQ1IBlHPJaELjwtCOykKGrz5MZGcu6nvPyOPUIoUX5U2VjjkPirSj4Ki3dtXp7ifPYvfF/NFXqQKoNZcznBlSijQplh64R7z+3eZAJ2r/EnYISaK5U+qOFLKitZVgvRhWsM7OVWClRq78RPR0aZ9fqIbS4kaF5eqXQDa0HyGo7LGP9bfdn8rb9zKulnvbJ43SWEtdwpuEBLK+WgtNu8GvHDuQnLCqf0tE/I7wXJW3dCZ47vwo87lzh2VnOM5Y3j0uMLFb9JKLj3FyjOR+WJ5r6D6Y
  template:
    metadata:
      name: frpc
      namespace: aviator
    type: Opaque
