creation_rules:
  - age: >-
      age1l8zxqe4wzxe4wd5dte27unc65ah2uwpcge7gdyx0k7v3ezwzapgqh62a3j,
      age1qrewprwahta2ffx0tmn5haqupaj3lj7l50pzf2e866p6490m45wqfp5cjk,
      age1q9lerkvzv78kcme2hkgn036ehqjjr9zt7kfxvdgt55e5z6fa840qn0ap3g,
      age1uqvs334h30qy5wp7jnzzdzg8wq9xrp2xdg80uw0apgcqtg9mme4qpgutgd
