apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-cni-plugins
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: install-cni-plugins
  template:
    metadata:
      labels:
        name: install-cni-plugins
    spec:
      tolerations:
        - operator: Exists
      initContainers:
        - name: install-cni
          image: ghcr.io/siderolabs/install-cni:v1.9.0@sha256:53bdeb6c8d238dd593ee75f265baf4625925a034d8d18f10ffeae88d7fcf2c3e
          command: ["/install-cni.sh"]
          volumeMounts:
            - name: cni-plugin
              mountPath: /host/opt/cni/bin/
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10@sha256:ee6521f290b2168b6e0935a181d4cff9be1ac3f505666ef0e3c98fae8199917a
      volumes:
        - name: cni-plugin
          hostPath:
            path: /opt/cni/bin