apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
  annotations:
    glance/icon: sh:rustfs
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/rustfs/rustfs
    path: helm/rustfs
    # renovate: datasource=github-releases packageName=rustfs/rustfs
    targetRevision: 1.0.0-beta.7
    helm:
      valuesObject:
        replicaCount: 1
        config:
          rustfs:
            region: "eu-west-4"
        mode:
          standalone:
            enabled: true
          distributed:
            enabled: false
        secret:
          existingSecret: rustfs-secret
        storageclass:
          name: longhorn
          dataStorageSize: 20Gi
          logStorageSize: 1Gi
        service:
          type: ClusterIP
        ingress:
          enabled: true
          className: tailscale
          hosts:
            - host: rustfs
              paths:
                - path: /
                  pathType: Prefix
          tls:
            enabled: true
            existingSecret:
              enabled: true
              name: rustfs-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
