---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBDMa4K42T3ezGAh1Kp1Zy6hs4pUiz+cTvAYk/8HZo+SlEfHUb4Y0mXYUct6BbPEO0pHdh64xwVQAtgLhZwEKFIp1pxOHEKf+2bkLU91NmvAk2uPRFpL//qUYuvKmzqKw7rOJOnv0sHIbs4Yi/h3e6uYDQDgxu0WVmT03O2oNJhbWWemKN20xVRsiWWB1aSXA2Oj30RUqosoo1XiPew8gT1W0wgt0hy4M/8ft5DfXTmjci/F0aBZPD1J//VqX1R4a82qurbSpxgIuTf+Tniih2LunyfVzA8GpXy6tUqA4kpZ/iuJdxOVoSWQF07shElcfIz1t11DPLWkRW4GWA+tnx0+gzpAYMTq+lOXVz70xo9X6UK3fV9JYz7QLamXyMDdDXpbHl/LJ1ImaE3Ch0EIrt7p5XKLRJJFjSXtoejUxMfXhqAyJwzACCMFTU/Nynp22Q8joORRsvZ5+jQrTPWwz/vTFH9VRpZAJneyEjPMhmLsiku6NWshIkBl3ciRg4+e4OcJcw6xXK8ELTSXZZFiAgMnwyHZKEQ/NdtmyPTH1sKX+gy/9UrhCgaL6p0Hi5v1itIRfgFt4+Lk0JiTAqFcFCJoYZNZjx/V17av3oDKQ3IwNqlQcQgIAk9cYszXkyHo1JVYrBwMhdyI/ThFpv4Gaq5HImkWGBhkHPsWJsaUGnC6kJpmyQPv9CnlJxNJ9DKB4eMfEXTKk1MmorRWKUorsrV5HdHZQ==
    RUSTFS_SECRET_KEY: AgCWIQJAVtX4B5ebcwyw/Ef4J5MHwB9xECtIwYp1R7mPu+H86TducOwPjdeLkUkWBv0rcwMXw/M/QRGCLkTSA1naG4HdQRAFzB/swn12vMUAicw7r1LcoKNHMdr9wkACUN6MnHM9rxinBE+2UGTn3buO0CwcpBtTXRjTsCYnpcocqC+5/TWLmWz4IuLwx6E5Aivy10bBaCiXnkAddIArMIiIVwQYwCeTdw11dV07smBvAqfTJVGRejVQF2jPn4Niu4zGksq8YAuTewckSbUGJQ70TXqqo+9imjgqiyG71XjqVs1SRnFE1RZqBHSum5i+E3hOnJfrp7Ra+iIEDZ5W7QkqTo5D7QovvcBrikAE5VpBtruMo1lSH6NLx1/9BYJ94cKBVYwJuamOQ44SiJgi+LZapK+IzFgTruEAusF+lGINnjoFhbbIIZ4N8F8dJPim7FWxDTnzDOHMOunlyx0NaXNdL7F03hOJKZIuw8IkQ62BjD4k78w/f4nkTiB9vhrRaPPixn2FURSGTmXPimE4vXRAzXR/V+0Bg4qvNcJCs1xbaL4fqiYJEjL1K5XX6N0DLzTxPu3LYMDo3j2lr/I3f11aLJusRnuBxdYjTPEO49ICp5kVA358tFygs6XgKBXzgCwptHs+4z50IeuVZOR2rxpya409IgYTQJWc3ketZeddDHzXE4W2ZBs2MiY+tstmgXF2S/NzbCpEQYEezZ4DB5IXJy21R3Ux1tVsesbUHohrdFl76WB48SwH
  template:
    metadata:
      name: rustfs-secret
      namespace: rustfs
    type: Opaque
