---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgCDUjBunhjml1X4rJMyMmdot8tRNbdOMElHqEDNcJmsd/YU9TUogGUAdUFURlCbo/NSjrtBsyWyjbV1Y32xr0QZw4GGedqogb68pJT+rn0nOWRqTtkBdiOf2yDQMaes9phlM5lYMbVduBBigP+uS1uN5zzj2tc2tjB5ZhjkYXAiiKj0snEYVN2d6+OFn7bRF/QvJiekO2MRsMOXdbW9dR9kLIeMSiDD+wg+BBR61eiIVOd4qAYT7xjILtS+vlFDbNR1l45LmxGQ7ux+mFnDtKqaGKdty5ciA8sFsxxd2zR/81IUSxfrk/tDk43Jv1HhqOPY3ShHVGOmtsBsiVRHuYQ7s1j+C+eUHDHGBL+D3dqDojBeh6Eb+T/k2xT1TzmmkPImBt3psSl99e35AuIJciJwIgCNMZnaUy9uAnHNocG7HJ9ZcczXVTsPkHk9goFDoqMp95V45o/9KFp+EYdDxgY4YHcrGxw2lgy/laKtsBeyCHqKlLyiyPzCGEabfhxY98MYC5IE4GZu1sN4EtXNK9sJ8a5uT+bjWtiBREjeBD23qKWdO4W8XkpHJKjsAQYOZVDNI3gpmYke+5ur+OqiJuHFC76YG+WeHrs6HBFzOkePyZwwQipDkXTJDqHmCVCksDTW7NPYJRjKVBPlHIqXRoezpFEHxjHbpKsofJcR97eokG2S91KgpNdA+4+Tm5nLAYUc0ZF69xPVOwyR6nHWqhz47VaS19xPahjXHClGgxOlNl4+22uaHWB6jB6+PbqlsD+8JhEzK6UjzXsBWNAe2HOm
  template:
    metadata:
      name: postgres-admin
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-user-passwords
  namespace: postgres
spec:
  encryptedData:
    ptcgl: AgCPiXxZxORyIEv4HhuqwDTKKulp2iXGXT5yKsFLPRk2vIdbuy2c/w0zVfUFhEz4cFMFudY1vazYMEOVEH31Ny0+KVO2OT12pOMNzUrQAp9v26G9qCVVJ8x+FlipsoblKSohzGeo7St8rYDevgYj9dtyJ6dVsmcqFz5L8YqCk9IZf7scSj/UJ4u5BoiZABk6Vo15oeXc/UJqg9XbchWQqEVgUGopjo8WqBMDLbSEFLMm/eXH2+ocGHIPC/yFb0LNmvKQUiWkzCo77lrCN9jPNYNwWjURL8nqRWgQNgkIahlwzH8p8xgL//XkMTpNBdwByeNxteaTshNRhUF3SMNKptGQyAkjxvWl8FFPb/3lBx7EiW3AnCi+fNGAL+ASq47vMyYnJb2GBhm+b0XKrFwBsopZ+l8vd/SIHJjOm3k93qZK2F+Cbm8zcHFFSSpC/DIBbHNbrunzNEfw0jXMnXgZxU9U994vQG20gkhX671yyHyKf8XkPKf/nP6RlRkHRS7e6vck/fu6ZxiyKAUDYfx32mbKS6vPI/eYbrvANpvy3P/N9RJjpPFahMJqwyWi0Hu13OzOcwLYYrx6QndqPCX95JfiSNgY+GnKbeMF3k6RzSPttTKw50dZNcjYGnYFv6E0g5ddIYrd8RJTpw7Xb5w2KIih6nAzMa/2xDqgr5ZiOFWGB55nQhQqPylNGJnBSm3dL7dcczGQsatR8VHrEG+DfCrkrOog7qzUGxafHIH35yDJsuc8rzR55CXgsBnI4OiGfOx88VpT/iIiMzy66zEBjrci
  template:
    metadata:
      name: postgres-user-passwords
      namespace: postgres
    type: Opaque
