---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgBEC4rQrRiorUEdfvn9thyufNUVbQhSAzv7g5aPSrcqGMgbzk2h89M6VR11IFf5f+y8YtkHHQOCiahck/zqQLb5K+SWLufSs30APSpHQ5W7X67//IDebtVlk1wnJBSYJVLVprwho8GtK6ywoPaRfAHYs0hULBChpS4cSrqjxu9zJHwxY4Xhneaeh3ZKUbhyZFWTdNzxvEcIXOXlc+IdRI2mb+r6L2h4tc3SDQO4GZgs1uQogGZ3Dv2EpAVV9KYdAqtAVzZ6snyS+RIYLtsfN51gpreAqD+WT9UI2mYNMEbF5aETeHgMkExDZ0Nh7YKMVwMHeCQqtt04i1F9n6Z31ynAXjeKy15rCAHWrPwEo6c1Xu9SSPhk2PfuPDadSHNS/13W4HiKkCbb5fMYeh/Y6La1EVgLQNRU8PMyC2iI+svZBkmM4pBOrY5et73dkfuneIcHRVfGd6Zt1a4RYZdc252clSZ6glzY0qFWRyZdOLYQ8rkX3UfwfckoaBf52sn/McmErnLJvElGELm3JoeIY1DYBC1TEJQFsG/gDkODr4/jmqGC5e7FPGlDRnhSKyvhiCy/UseRZkG9XbYrx3yYI1wuagkWV283h5GcPn0zqP45seTmQ08rVVa9PNUYJCwf0ELEwOFQ4a54wKquH9AZxq/IuvA++aeRaQJwxfk66ODVg+1A6G7Gqz0MHih6FZZOSB4wk6Y+TbqBoUueiy+Ra/Ask66NdwPj/A76SRIkg+YOqgKYQkxuec6GWX1sUDgZj1oAOUUt0xIB/7gPzBp9oApq
  template:
    metadata:
      name: postgres-admin
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-user-passwords
  namespace: postgres
spec:
  encryptedData:
    aviator: AgAVfXAVnK4NfOBSildQi7BcHZiAPHFZP1LD6Bo3ATrsoGN01ntAf7Up+l2GD7UOOpXgb5aTQ1XC/vVXd5h+C2OegZIOH7YWLeP5Zndy1o6VTrcgBhHulmqNSFBFj89IKgAmSOHWMBypDWHQUxEPaMX1gM1nrA834u4K9RtdJBPnczMeORU2GK3V1fCtMGqyJhWyCxCEyOL7ryj0xF6GS58VNDgl9BkrLpXpiIO7T+GbHR1FYwdsEg4xymq0/iE6+mZRFSqbjG2oWQYJSil2Srq5azkbKiXblWs/9StTnVgZsXByIkIC5RaHbxUTopf2asyMQmKCm70onut773YlBPiccn8YDXHzbB1iyZfIEz1E4+euMOpXSxPAX8dSkBCoKkvvV1b4LcYvg8+Y0myzmeIUaRgC1Cvx1n9cvhrv+2j9MgGKRlfu5YCvBNuSBvGa0cKkISpYNFnTelzQ/m/GxgA39O2VcsUAQr6rheYJV1zNvS1ZDOKmy+AkAc/X+dVK/AHm9Xwv/MgkFd6vidUxxvTwIc+th/EHiSyVwoZM8SawF/IH+ydgn1MhestYdvw55kV4jDxt0ZKPDzfaw1ERfpy6cFnW1QRe+0Jyb3IvczEGwUJfnhGgshkC1qCcIRVC4hNtW1y2HF30KnWjA3nr9Cn9SzRrkpAdY8yI1v+7872aORisE18mFSq4qIx5VUKs4z/5Ke0feHqz3yiS6aOS2+WbiUk2XRc4tQjB6srZXIOoarno11HzeWhtTftAIgGgJ0Lnzg5CZPi95fz9OsYEya0J
    ptcgl: AgB2xA9TXDhRoLQ4mbcaflZAbHLq/OwBAnVKvi7AIQIIbPfcDVGKEC91XHg+sLCEbhMs0DAnPUBq1zFopcIg76Q7jEaUiASSjblbBYv5fYUw+0hZQKbYXwTlUvi5aoH+Eo1+PGauymqTinr8NNYLK82NLwyJC2PiIw0ihwlqKwTqW5Xt9AiwqGirdzMdWuDIAXwFi65q6CD4lS2E7F54yhEkdUHXR1bZrIy44EN+F11hq7X3s743gvW0dSc/ekZFELJSIgE5jC03gxJ0JJkNBEMmP7A8BOWJKcnzttD5kEuO/PcZzvX3ktz/hPRHPWkiSL2PbjzezxhcrMByClYy/euxlch/pgXYd/+oKgoD0FnTmMO6hVkjKGLUQMBY0Ld82jYxEt8GTxtJ6/nVkoCBxOV7VQXbq2ISgKCodffzh4csRQvUhAJr9dK1IF7W3fmyoQn1yjCCg5EvHpR4D4u9tvDqEEPlxSqT4NueuD8mqQ2SmZ+gofo6v09weXF52/4uxrP60FzznVYhRKLWVwg3PzJWKYbAVgTBmv8XDZVXEVgvkADMyJKEHTuqwUrftewiMYipPcjmy3JCaGllCcWpWHJ5M29UjFyPwt2R4tNUQZPwIwzbsM5pR9whF0+9lGA8K0l4rh1m8tMu2pGOCXJGR4LLu6WsPeulXmTRPoqvpjZJ2uQlN8A4AeXMIp8i+zI2WjOTlEZP2nOwuS/8a10XjwPueS6L1FzbV+kb7HPGKey4B97CS9/rkpGQ/Ol9G2KwIBwpggiFZWFZFHkEJilP6DSq
  template:
    metadata:
      name: postgres-user-passwords
      namespace: postgres
    type: Opaque
