---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: glance-secrets
  namespace: glance
spec:
  encryptedData:
    TAILSCALE_API_KEY: AgAoMfuh/OnFag1nXwGMVGE0hWZLbQ8Cvg+87sRvxYE9OhuwX1zITB+i1CrpGpzx1jtqvrr8vDUSRkIuop2BLQNFN3uvXr9WmYqmBgTvq/MbtWjw9zBIcFbgeRKvQRr6YveilmAnpTLShotMoowCSh13ASTHTaTeebAHYAil/owfpKptxPI54jQL2P+ZDIZuCp1XEOP5nArvo5fy2Cy3tbeclkxVY3H0uU55ytIUh1bcx1ND3iU1sIHAxvTwfA7jpktAG7UCntin/MAh9Kxa9C7m0kQTvma91CJ5+jIUszsrG1GCgrSdFtQtwznP7BpW2EXISh8rk96+AUtwmkR+4bSDvRBNlrwUYrWVOQHu2hNIY6tFSDlFRHA4XQM2sfb32CqeziBnJgsLOa3+AIWvBjFdhGcgnL1KxOGbOgrUCRkuZrRwRISZ9CE92bH5lH6sW3qHextFteZLJnS/VcxgYd1KZYJkX4Q/Rap0M+CI77OcIePr8jXdFRY9KYKZdl1/nFNWuoU7B17taC8RCR1iALhOm0HMcG2cfv3grRhwhNZ0TZUFTmP4jv0HCEc9iQvua0kFGVWFpxMrmYJv/LSSesgaHZT0qCWFhaOMJFXT3gw4LpNHaB3e7YL/hPX+nsuzw7aTO9vqff64IKsHnES0cGEN9RCDvcBsf0txb6FMLqUcE0b3b1vuuJlw7YWCnJuK/QwPkybOCNJzu7/hU4KTWIdlY5Io1VkKOZEAkJzAzU+zM5qpNofzKxUIUSJ2mmEqfDYZtFuDKa1nNbCfuK+O
  template:
    metadata:
      name: glance-secrets
      namespace: glance
    type: Opaque
