apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd
  - cloudflare
  - echo
  - glance
  - longhorn
  - metric-server
  - monitoring
  - netbox
  - ptcgl
  - postgresql
  - rustfs
  - sealed-secrets
  - tailscale
