apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd/
  - cloudflare/
  - docker-registry/
  - echo/
  - longhorn/
  - minio/
  - monitoring/
  - sealed-secrets/
  - tailscale/
