---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frpc
  namespace: minecraft
spec:
  encryptedData:
    token: AgBC/heFP7W5jTZ1EGnmDEmglT/P0gQ2gwrXca0y010cprtL1QSAeSVF+/9edeWIzmgx0jR550ljeADkiUsGnRGD4E7X1J/W66WyuWiQF1VlOEMsWjY8RSJdbiunBqJBxv4nGr7yVDghbjdqInhmx++XTFFoRizTW1dtLJJNzWg6mMNM66ywUhEdzpRBorBDRjZROOBah8m4RxFWPrFkMknWoS4Zsw4YaU46mO2maNTkYYAy/Gw0Bklxm7gNM6/Vftg5aKSqepPCscI0+1i+/gNYNzVozroN0ylRsaY7Khv+PfpbVPV7idHrtFFMk0IW1WXS19TfBHxKjolNx4tgMfSSThzHicfZz06EQ7BqL50ONfnyV7T8wOeLz7lWYpdiw8oSuyoIOUdkSEGQWvAZOIVF5GlT/80HJjhjWibNqRmbkoinw6jkWDkB+N/uj1yCWaFmOZ0ieeh+W+rzXuZOtAYhM2LXY9BM2zFabBMaNswkbf2+uBD1uc6aFAFNfwZxRdB/vbxx8nEX2xO83kuEhaV2mHyR9Bdb8/tloLp5F6AgBGaY7Yo+M/7OEnb34HMuTaXad6MSNdKfdk/aD8cQy31dP1jePm9sUKryccc/vgJr9GgpHIM7WkcBV6r10Zz7BphU3aiaomqrywmBQeQPnZYk6iXFfHPKDTVSyf90xSUXkLDa497KTNQv6r5vZmsISTV57p96wt3IW6HYCuBEzaOAsRyETEucbjXY9lbMXCUrSwZgeKaCRAOlYpghkBBulWalF3sT2PpjbHoXONQeqKSq
  template:
    metadata:
      name: frpc
      namespace: minecraft
    type: Opaque
