---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAEwnnfiaULXZnS4NYNblZg36rLbSsZPG8T1I6A5XrmoGusYpWK5qaaN/ikq4VxZwpnDHlRZiTenw9l+lWCVgj2V/5oaa8Aryb+xOoT+jnSXrBhzXAj20OdNYGb5Uhn9vcwW1HSSSFDtTkTjNu3RFQx+q76jmj8podQz5BL/nqwzgk3RgnxWOEHDgOrBMv/ExYYmYMDnpcVBxM6sKfAWM4nydWfE5jaamsWv+R5rL8g52LXSo+SUgRy7N7ZXN8Kh3HAgPhOE3BfV/dVmu2VkliunPjqKkNMuXO0mXDZbjYAzGC/N4hofl0J5BK8N6MXae2ZUt4a4XxJ01BnROE210Bqkd9E7q/zETmsU7U5CauCSeMdrHU7NYoRGFJiRb2sWdH0tBEOe82OyQSFfUr9JzZqpTZ+wbDRFLj/GzeYBvzxOsUs06VyOmBx87gHtBIv9ieqHKf/9U+IOKXXtKGQRyCAJv31VSD3XgaZmr278SCLVjY3vLlJ61JyY2HkRgH9l0FMJa8S/bfGklG4k6vnKvxVwADHE3gKD3CIAX8ZUyLymi1KmIb7Z94rqV0iS9Ld5FxLYZycwLs3LCoyo9Om8mR4yT443m85zOoUPsxp9gkclmSj+aJtKQvM0KRu97V0unxTS2SFp2faYZVlrNxM4MQxQ4kxttjiJ65zmOAEATrEVluHqgOs5WtOh5wCR8pC49nzjhP18JjLwOIOb2T5/ZgRHJrJjrsDfKTazaNTMo7BD4JURmbQwFtjhPEyBHjJcEJFmLXx2NcPe1GAqu1lXFlTwc1ZcUiwtw91tZhAYfQ/dF6HXwVLibvZ8xCofDUR80ElGzqXBYsFH4za7NVHxQ/3mqiiJl+yewFGjcvxx3Od09ZpgVfZhKvnzvva980GMlPnJ+m2vd2e/dfPv4tI89sT5AYBP/C9aB2JPhEMCRbdd8Mljom48d6qrw==
  template:
    metadata:
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
