apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "ptcgl"
      images:
        - alias: "web"
          imageName: "ghcr.io/zwolsman/ptcgl-web:latest"
          commonUpdateSettings:
            updateStrategy: digest
        - alias: "api"
          imageName: "ghcr.io/zwolsman/ptcgl-api:latest"
          commonUpdateSettings:
            updateStrategy: digest
        - alias: "assets"
          imageName: "ghcr.io/zwolsman/ptcgl-assets:latest"
          commonUpdateSettings:
            updateStrategy: digest
        - alias: "sync"
          imageName: "ghcr.io/zwolsman/ptcgl-sync:latest"
          commonUpdateSettings:
            updateStrategy: digest
    - namePattern: "aviator"
      images:
        - alias: "app"
          imageName: "ghcr.io/zwolsman/go-aviator:latest"
          commonUpdateSettings:
            updateStrategy: digest
